[unstable]
# cross compile core library for custom target
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
# points to file in project root
target = "monnos_x86.json"
